// <auto-generated />
namespace Supplier_Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Sexta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sexta));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211102199_Sexta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
