// <auto-generated />
namespace Sale_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Cuarta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cuarta));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211113541_Cuarta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
