// <auto-generated />
namespace Sale_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Tercera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tercera));
        
        string IMigrationMetadata.Id
        {
            get { return "202001290805002_Tercera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.Getstring("Target"); }
        }
    }
}
